spring.application.name=ProjectADN
# DB config (s?a username/password c?a b?n)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=adn_system;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate auto create table
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
# Spring Mail Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nhuthonkai1@gmail.com
spring.mail.password=brdy shnw vpnx oghe# mã b?n v?a nh?n
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true